# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jax-practice',
                'doc_host': 'https://birkhoffg.github.io',
                'git_url': 'https://github.com/birkhoffg/jax-practice',
                'lib_path': 'jax_practice'},
  'syms': { 'jax_practice.data_preprocessor': { 'jax_practice.data_preprocessor._check_xs': ( 'data_preprocessor.html#_check_xs',
                                                                                              'jax_practice/data_preprocessor.py')}}}
