# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data_preprocessor.ipynb.

# %% ../nbs/00_data_preprocessor.ipynb 2
from __future__ import annotations
import jax
import jax.numpy as jnp
import numpy as np

# %% auto 0
__all__ = []

# %% ../nbs/00_data_preprocessor.ipynb 5
def _check_xs(xs: np.ndarray, name: str):
    """Check if `xs` is a 1D array with shape (n_samples,) or a 2D array with shape (n_samples, 1)."""
    if xs.ndim > 2 or (xs.ndim == 2 and xs.shape[1] != 1):
        raise ValueError(f"`{name}` only supports array with a single feature, but got shape={xs.shape}.")
